app/urls.py
from django.urls import path

from app.views import home_view, contact_view, about_view, historique_view

app_name = 'app'
urlpatterns = [
    path('', home_view, name='home'),
    path('contact', contact_view, name='contact'),
    path('about', about_view, name='about'),
    path('about/<int:id>/', about_view, name='about_detail_id'),
    path('historique', historique_view, name='historique')
]

catsr/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path


from django.contrib.sitemaps.views import sitemap
from .sitemaps import BulletinSitemap, EvenenementSitemap, FormationSitemap, StaticViewSitemap


sitemaps = {
    'bulletins-view' : BulletinSitemap,
    'evenement-view' : EvenenementSitemap,
    'formations-view' : FormationSitemap,
    'static': StaticViewSitemap,
    }


urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('app.urls')),
    path('bulletins/', include('bulletins.urls')),
    path('formations/', include('formations.urls')),
    path('evenement/', include('evenement.urls')),
    path('@catsr', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

handler400 = 'handlers.views.handler400'
handler403 = 'handlers.views.handler403'
handler404 = 'handlers.views.handler404'
handler500 = 'handlers.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evenement/urls.py
from django.urls import path

from evenement.views import event_view, event_detail

app_name = 'event'
urlpatterns = [
    path('', event_view, name='event'),
    path('event_detail/<slug:slug>/', event_detail, name='event_detail'),
    path('event_detail/<int:id>/', event_detail, name='event_detail_id'),
]

templates/pages/event/event.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Evenements sociaux{% endblock %}

    {% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock style %}

{% block content %}
<div class="slider-area2">
    <!-- <div class="slider-height2 d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        
                    </div>
                </div>
            </div>
        </div> -->
    <div class="hero-cap hero-cap2 pt-20 text-center">
        <h2>Evenements sociaux</h2>
    </div>
</div>

<!-- Hero End -->
  <!-- Our Cases Start -->
    <div class="our-cases-area section-padding30">
        <div class="container">
            <div class="row">
                {% for event in event_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-cases mb-40">
                            <div class="cases-img">
                                <img src="{{event.img_evenement.url}}" width="300" height="200" alt="{{ event.titre_evenement }}">
                            </div>
                            <div class="cases-caption">
                                <h3><a href="{% url 'event:event_detail' event.slug %}">{{ event.titre_evenement| capfirst|truncatewords:10 }}</a></h3>
                                <!-- / progress -->
                                <div class="prices d-flex justify-content-between">
                                    <p><i class="fa fa-eye" aria-hidden="true"></i><span> {{ event.nombre_vues }}</span></p>
                                    <p><i class="far fa-clock"></i><span> {{ event.created|timesince }}</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination d-flex justify-content-center py-4">
                <span class="step-links">
                    {% if formation_list.has_previous %}          
                        <a href="?page={{ formation_list.previous_page_number }}">Page précédente</a>
                    {% endif %}

                    <span class="current">
                    {{ formation_list.number }}
                    </span>

                    {% if formation_list.has_next %}
                        <a href="?page={{ formation_list.next_page_number }}">Page suivante</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <!-- Our Cases End -->


{% endblock content %}

templates/pages/event/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}
{% block title %} {{ event.titre_evenement}} {% endblock %}

{% block content %}

  <!--? Blog Area Start -->
  <section class="blog_area single-post-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                <div class="single-post">
                    <div class="blog_details">
                        <h2 style="color: #2d2d2d;">
                            {{ event.titre_evenement|upper }}
                        </h2>
                        <ul class="blog-info-link mt-3 mb-4">
                            <li><a href="#"><i class="fa fa-eye"></i>{{ event.nombre_vues }}</a></li>
                            <li><a href="#"><i class="fa fa-clock"></i>: {{ event.created|timesince }}</a></li>
                        </ul>
                    </div>
                    <div class="navigation-top">
                        <div class="d-sm-flex justify-content-between text-center">
                            <p class="like-info"><span class="align-middle"><i class="fa fa-edit"></i></span>
                                {{ event.editeur }}
                            </p>
                            <ul class="social-icons">
                                <li><a href="">
                                        <i class="fa fa-facebook-f"></i>
                                        {% post_to_facebook event.get_absolute "Facebook" %}
                                    </a>
                                </li>
                                <li><a href="#"><i class="fb fa-twitter"></i>
                                        {% post_to_twitter "{{event.slug}}." event.get_absolute_url "Twitter" %}
                                    </a></li>
                                <li><a href="#"><i class="fa fa-whatsapp"></i>
                                        {% post_to_whatsapp event.get_absolute_url "WhatsApp" %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="feature-img">
                        <img class="img-fluid" src="{{event.img_evenement.url}}" width="800px" height="500px" alt="{{ event.titre_evenement }}">
                    </div>
                    <div class="blog_details">
                        <div class="excert">
                            {{ event.content_evenement | safe }}
                        </div>
                    </div>
                </div>

            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title" style="color: #2d2d2d;">Voir aussi...</h3>
                        {% for event in event_list %}
                            <div class="media post_item">
                                <img src="{{event.img_evenement.url}}" width="80px" height="80px" alt="{{ event.titre_evenement }}">
                                <div class="media-body">
                                    <a href="{% url 'event:event_detail' event.slug %}">
                                        <h3 style="color: #2d2d2d;">{{ event.titre_evenement|truncatechars:22 }}</h3>
                                    </a>
                                    <p>{{ event.created|timesince }}</p>
                                </div>
                            </div>
                        {% endfor %}
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
 <!-- Blog Area End -->

{% endblock content %}