app/urls.py
from django.urls import path

from app.views import home_view, contact_view, about_view, historique_view

app_name = 'app'
urlpatterns = [
    path('', home_view, name='home'),
    path('contact', contact_view, name='contact'),
    path('about', about_view, name='about'),
    path('about/<int:id>/', about_view, name='about_detail_id'),
    path('historique', historique_view, name='historique')
]

catsr/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path


from django.contrib.sitemaps.views import sitemap
from .sitemaps import BulletinSitemap, EvenenementSitemap, FormationSitemap, StaticViewSitemap


sitemaps = {
    'bulletins-view' : BulletinSitemap,
    'evenement-view' : EvenenementSitemap,
    'formations-view' : FormationSitemap,
    'static': StaticViewSitemap,
    }


urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('app.urls')),
    path('bulletins/', include('bulletins.urls')),
    path('formations/', include('formations.urls')),
    path('evenement/', include('evenement.urls')),
    path('@catsr', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

handler400 = 'handlers.views.handler400'
handler403 = 'handlers.views.handler403'
handler404 = 'handlers.views.handler404'
handler500 = 'handlers.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

formations/urls.py
from django.urls import path

from formations.views import formations_view, formations_detail

app_name = 'formations'
urlpatterns = [
    path('', formations_view, name='formations'),
    path('formations/<slug:slug>/', formations_detail, name='formations_detail'),
    path('formations/<int:id>/', formations_detail, name='formations_detail_id')
]

formations/models.py
from django.db import models
from django.db.models.signals import pre_save
from catsr.utils import unique_slug_generator_formation

from tinymce import HTMLField

# Create your models here.
class Formation(models.Model):
    """
    docstring
    """
    titre_formation = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, unique=True, help_text='Laissez ce champ vide')
    img_formation = models.ImageField(upload_to='formations_img/')
    content_formation = HTMLField('content_formation')
    editeur = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=False)
    nombre_vues = models.IntegerField(default=0, verbose_name="Nombre des vues")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('formations:formations_detail_id', args=[str(self.id)])

    def __str__(self):
        return self.titre_formation


def tag_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator_formation(instance)

pre_save.connect(tag_pre_save_receiver, sender=Formation)

formations/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from formations.models import Formation
# Create your views here.

def formations_view(request):
    """
    docstring
    """
    formation = Formation.objects.all().order_by('-created')
    paginator = Paginator(formation, 9)
    page = request.GET.get('page')
    try:
        formation_list = paginator.page(page)
    except PageNotAnInteger:
        formation_list = paginator.page(1)
    except EmptyPage:
        formation_list = paginator.page(paginator.num_pages)
    context = {
        'formation_list': formation_list,
    }
    template_name = 'pages/formations/formations.html'
    return render(request, template_name, context)

def formations_detail(request, slug):
    """
    docstring
    """
    formation = get_object_or_404(Formation, slug=slug)
    formation_list = Formation.objects.all().order_by('-created')[:5]
    formation.nombre_vues = formation.nombre_vues+1
    formation.save()
    context = {
        'formation': formation,
        'formation_list': formation_list
    }
    template_name = 'pages/formations/formations-detail.html'
    return  render(request, template_name, context)

templates/pages/formations/formations-detail.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}
{% block title %}{{ formation.titre_formation }} {% endblock %}

{% block content %}

    <!--? Hero Start -->

     <!-- Hero End -->
     <!--? Blog Area Start -->
     <section class="blog_area single-post-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 posts-list">
                    <div class="single-post">
                        <div class="blog_details">
                            <h2 style="color: #2d2d2d;">
                                {{ formation.titre_formation|upper }}
                            </h2>
                            <ul class="blog-info-link mt-3 mb-4">
                                <li><a href="#"><i class="fa fa-eye"></i>{{ formation.nombre_vues }}</a></li>
                                <li><a href="#"><i class="fa fa-clock"></i>: {{ formation.created|timesince }}</a></li>
                            </ul>
                        </div>
                        <div class="navigation-top">
                            <div class="d-sm-flex justify-content-between text-center">
                                <p class="like-info"><span class="align-middle"><i class="fa fa-edit"></i></span>
                                    {{ formation.editeur }}
                                </p>
                                <ul class="social-icons">
                                    <li>
                                        <a href="">
                                            <i class="fa fa-facebook-f"></i>
                                            {% post_to_facebook formation.get_absolute "Facebook" %}
                                        </a>
                                    </li>
                                    <li><a href=" "><i class="fa fa-twitter"></i>
                                            {% post_to_twitter "{{formation.slug}}." formation.get_absolute_url "Twitter" %}
                                        </a></li>
                                    <li><a href="#"><i class="fa fa-whatsapp"></i>
                                            {% post_to_whatsapp formation.get_absolute_url "WhatsApp" %}
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="feature-img">
                            <img class="img-fluid" src="{{formation.img_formation.url}}" width="800px" height="500px" alt="{{ formation.titre_formation }}">
                        </div>
                        <div class="blog_details">
                            <div class="excert">
                                {{ formation.content_formation | safe }}
                            </div>
                        </div>
                    </div>
                    
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title" style="color: #2d2d2d;">Voir aussi...</h3>
                            {% for formation in formation_list %}
                                <div class="media post_item">
                                    <img src="{{formation.img_formation.url}}" width="80px" height="80px" alt="{{ formation.titre_formation }}">
                                    <div class="media-body">
                                        <a href="{% url 'formations:formations_detail' formation.slug %}">
                                            <h3 style="color: #2d2d2d;">{{ formation.titre_formation|truncatechars:22 }}</h3>
                                        </a>
                                        <p>{{ formation.created|timesince }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
     <!-- Blog Area End -->

{% endblock content %}

templates/pages/formations/formations.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Formations{% endblock %}

    {% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock style %}

{% block content %}


    <!--? Hero Start -->
        <div class="slider-area2">
            <!-- <div class="slider-height2 d-flex align-items-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-xl-12">
                                
                            </div>
                        </div>
                    </div>
                </div> -->
            <div class="hero-cap hero-cap2 pt-20 text-center">
                <h2>Nos Formations</h2>
            </div>
        </div>
    <!-- Hero End -->
    <!-- Our Cases Start -->
    <div class="our-cases-area section-padding30">
        <div class="container">
            <div class="row">
                {% for formation in formation_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-cases mb-40">
                            <div class="cases-img">
                                <img src="{{formation.img_formation.url}}" width="300" height="200" alt="{{ formation.titre_formation }}">
                            </div>
                            <div class="cases-caption">
                                <h3><a href="{% url 'formations:formations_detail' formation.slug %}">{{ formation.titre_formation| capfirst|truncatewords:10 }}</a></h3>
                                <!-- / progress -->
                                <div class="prices d-flex justify-content-between">
                                    <p><i class="fa fa-eye" aria-hidden="true"></i><span> {{ formation.nombre_vues }}</span></p>
                                    <p><i class="far fa-clock"></i>:<span> {{ formation.created|timesince }}</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination d-flex justify-content-center py-4">
                <span class="step-links">
                    {% if formation_list.has_previous %}          
                        <a href="?page={{ formation_list.previous_page_number }}">Page précédente</a>
                    {% endif %}

                    <span class="current">
                    {{ formation_list.number }}
                    </span>

                    {% if formation_list.has_next %}
                        <a href="?page={{ formation_list.next_page_number }}">Page suivante</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <!-- Our Cases End -->

{% endblock content %}