app/urls.py
from django.urls import path

from app.views import home_view, contact_view, about_view, historique_view

app_name = 'app'
urlpatterns = [
    path('', home_view, name='home'),
    path('contact', contact_view, name='contact'),
    path('about', about_view, name='about'),
    path('about/<int:id>/', about_view, name='about_detail_id'),
    path('historique', historique_view, name='historique')
]

bulletins/urls.py
from django.urls import path

from bulletins.views import bulletin_view, bulletin_detail

app_name = 'bulletin'
urlpatterns = [
    path('', bulletin_view, name='bulletin'),
    path('bulletin/<slug:slug>/', bulletin_detail, name='bulletin_detail'),
    path('bulletin/<int:id>/', bulletin_detail, name='bulletin_detail_id')
]

catsr/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path


from django.contrib.sitemaps.views import sitemap
from .sitemaps import BulletinSitemap, EvenenementSitemap, FormationSitemap, StaticViewSitemap


sitemaps = {
    'bulletins-view' : BulletinSitemap,
    'evenement-view' : EvenenementSitemap,
    'formations-view' : FormationSitemap,
    'static': StaticViewSitemap,
    }


urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('app.urls')),
    path('bulletins/', include('bulletins.urls')),
    path('formations/', include('formations.urls')),
    path('evenement/', include('evenement.urls')),
    path('@catsr', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

handler400 = 'handlers.views.handler400'
handler403 = 'handlers.views.handler403'
handler404 = 'handlers.views.handler404'
handler500 = 'handlers.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bulletins/models.py
from django.db import models
from django.db.models.signals import pre_save
from catsr.utils import unique_slug_generator

from tinymce import HTMLField

# Create your models here.
class Bulletin(models.Model):
    """
    docstring
    """
    titre_bulletin = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, unique=True, help_text='Laissez ce champ vide')
    img_bulletin = models.ImageField(upload_to='bulletin_img/')
    content_bulletin = HTMLField('content_bulletin')
    editeur = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=False)
    nombre_vues = models.IntegerField(default=0, verbose_name="Nombre des vues")

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('bulletin:bulletin_detail_id', args=[str(self.id)])

    def __str__(self):
        return self.titre_bulletin


def tag_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(tag_pre_save_receiver, sender=Bulletin)

bulletins/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from bulletins.models import Bulletin
# Create your views here.
def bulletin_view(request):
    """
    docstring
    """
    bulletin = Bulletin.objects.all().order_by('-created')
    paginator = Paginator(bulletin, 9)
    page = request.GET.get('page')
    try:
        bulletin_list = paginator.page(page)
    except PageNotAnInteger:
        bulletin_list = paginator.page(1)
    except EmptyPage:
        bulletin_list = paginator.page(paginator.num_pages)
    context = {
        'bulletin_list': bulletin_list,
    }
    template_name = 'pages/bulletins/bulletins.html'
    return render(request, template_name, context)

def bulletin_detail(request, slug):
    """
    docstring
    """
    bulletin = get_object_or_404(Bulletin, slug=slug)
    bulletin_list = Bulletin.objects.all().order_by('-created')[:5]
    bulletin.nombre_vues = bulletin.nombre_vues+1
    bulletin.save()
    context = {
        'bulletin': bulletin,
        'bulletin_list': bulletin_list
    }
    template_name = 'pages/bulletins/bulletin-detail.html'
    return  render(request, template_name, context)

templates/pages/bulletins/bulletin-detail.html
{% extends 'base.html' %}
{% load static %}
{% load social_share %}
{% block title %}{{ bulletin.titre_bulletin }} {% endblock %}


{% block style %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock style %}

{% block content %}

<!--? Blog Area Start -->
<section class="blog_area single-post-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 posts-list">
                <div class="single-post">
                    <div class="blog_details pb-5">
                        <h1 style="color: #2d2d2d;" style="font-size: 28px;">
                            <strong>{{ bulletin.titre_bulletin |upper }}</strong>
                        </h1>
                        <ul class="blog-info-link mt-3 mb-4">
                            <li><a href="#!"><i class="fa fa-user"></i>N° {{ bulletin.id }}</a></li>
                            <li><a href="#!"><i class="fa fa-eye"></i>{{ bulletin.nombre_vues }}</a></li>
                        </ul>
                    </div>
                    <div class="navigation-top">
                        <div class="d-sm-flex justify-content-between text-center">
                            <p class="like-info">
                                <span class="align-middle">
                                    <i class="fa fa-edit"></i>
                                </span>
                                {{ bulletin.editeur }}
                            </p>
                            <ul class="social-icons">
                                <li>
                                    <a href="">
                                        <i class="fa fa-facebook-f"></i>
                                        {% post_to_facebook bulletin.get_absolute "Facebook" %}
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-twitter"></i>
                                        {% post_to_twitter "{{bulletin.slug}}." bulletin.get_absolute_url "Twitter" %}
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <i class="fa fa-whatsapp"></i>
                                        {% post_to_whatsapp bulletin.get_absolute_url "WhatsApp" %}
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="feature-img">
                        <img class="img-fluid" src="{{bulletin.img_bulletin.url}}" width="800px" height="500px"
                            alt="{{ bulletin.titre_bulletin }}">
                    </div>
                    <div class="blog_details">
                        <div class="excert">
                            {{ bulletin.content_bulletin | safe }}
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget popular_post_widget">
                        <h3 class="widget_title" style="color: #2d2d2d;">Voir aussi...</h3>
                        {% for bulletin in bulletin_list %}
                        <div class="media post_item">
                            <img src="{{bulletin.img_bulletin.url}}" width="80px" height="80px"
                                alt="{{ bulletin.titre_bulletin }}">
                            <div class="media-body">
                                <a href="{% url 'bulletin:bulletin_detail' bulletin.slug %}">
                                    <h3 style="color: #2d2d2d;">{{ bulletin.titre_bulletin|truncatechars:22 }}</h3>
                                </a>
                                <p>{{ bulletin.created|timesince }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Blog Area End -->

{% endblock content %}

templates/pages/bulletins/bulletins.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Activités{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock style %}

{% block content %}

    <!--? Hero Start -->
    <div class="slider-area2">
        <!-- <div class="slider-height2 d-flex align-items-center">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        
                    </div>
                </div>
            </div>
        </div> -->
        <div class="hero-cap hero-cap2 pt-20 text-center">
            <h2>Activités</h2>
        </div>
    </div>
    <!-- Hero End -->
    <!-- Our Cases Start -->
    <div class="our-cases-area section-padding30">
        <div class="container">
            <div class="row">
                {% for bulletin in bulletin_list %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-cases mb-40">
                            <div class="cases-img">
                                <img src="{{bulletin.img_bulletin.url}}" width="300" height="200" alt="{{ bulletin.titre_bulletin }}">
                            </div>
                            <div class="cases-caption">
                                <h3><a href="{% url 'bulletin:bulletin_detail' bulletin.slug %}">{{ bulletin.titre_bulletin| capfirst |truncatewords:10 }}</a></h3>
                             
                                <div class="prices d-flex justify-content-between">
                                    <p>Bulletin N°:<span> {{ bulletin.id }}</span></p>
                                    <p><i class="fa fa-eye" aria-hidden="true"></i><span> {{ bulletin.nombre_vues }}</span></p>
                                    
                                    <p><i class="far fa-clock"></i>:<span> {{ bulletin.created|timesince }}</span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="pagination d-flex justify-content-center py-4">
                <span class="step-links">
                    {% if bulletin_list.has_previous %}          
                        <a href="?page={{ bulletin_list.previous_page_number }}">Page précédente</a>
                    {% endif %}

                    <span class="current">
                    {{ bulletin_list.number }}
                    </span>

                    {% if bulletin_list.has_next %}
                        <a href="?page={{ bulletin_list.next_page_number }}">Page suivante</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    <!-- Our Cases End -->

{% endblock content %}