app/urls.py
from django.urls import path

from app.views import home_view, contact_view, about_view, historique_view

app_name = 'app'
urlpatterns = [
    path('', home_view, name='home'),
    path('contact', contact_view, name='contact'),
    path('about', about_view, name='about'),
    path('about/<int:id>/', about_view, name='about_detail_id'),
    path('historique', historique_view, name='historique')
]

bulletins/urls.py
from django.urls import path

from bulletins.views import bulletin_view, bulletin_detail

app_name = 'bulletin'
urlpatterns = [
    path('', bulletin_view, name='bulletin'),
    path('bulletin/<slug:slug>/', bulletin_detail, name='bulletin_detail'),
    path('bulletin/<int:id>/', bulletin_detail, name='bulletin_detail_id')
]

catsr/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path


from django.contrib.sitemaps.views import sitemap
from .sitemaps import BulletinSitemap, EvenenementSitemap, FormationSitemap, StaticViewSitemap


sitemaps = {
    'bulletins-view' : BulletinSitemap,
    'evenement-view' : EvenenementSitemap,
    'formations-view' : FormationSitemap,
    'static': StaticViewSitemap,
    }


urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', include('app.urls')),
    path('bulletins/', include('bulletins.urls')),
    path('formations/', include('formations.urls')),
    path('evenement/', include('evenement.urls')),
    path('@catsr', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
]

handler400 = 'handlers.views.handler400'
handler403 = 'handlers.views.handler403'
handler404 = 'handlers.views.handler404'
handler500 = 'handlers.views.handler500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evenement/urls.py
from django.urls import path

from evenement.views import event_view, event_detail

app_name = 'event'
urlpatterns = [
    path('', event_view, name='event'),
    path('event_detail/<slug:slug>/', event_detail, name='event_detail'),
    path('event_detail/<int:id>/', event_detail, name='event_detail_id'),
]

formations/urls.py
from django.urls import path

from formations.views import formations_view, formations_detail

app_name = 'formations'
urlpatterns = [
    path('', formations_view, name='formations'),
    path('formations/<slug:slug>/', formations_detail, name='formations_detail'),
    path('formations/<int:id>/', formations_detail, name='formations_detail_id')
]

templates/nav/footer.html
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock style %}

<div class="footer-wrapper section-bg2" data-background="{% static 'img/gallery/footer_bg.png' %}">
    <!-- Footer Top-->
    <div class="footer-area footer-padding">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
                <div class="single-footer-caption mb-50">
                    <div class="single-footer-caption mb-30">
                        <div class="footer-tittle">
                            <div class="footer-logo mb-20">
                                <a href="{% url 'app:home' %} "><img src="{% static 'img/logo/logo2_footer.png' %}" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Contact Info</h4>
                            <ul>
                                <li>
                                    <p>Siège national : 38, Avenue Mbanza Boma, Q/ Adoula C/ bandalungwa, Ville de Kinshasa, RDC.</p>
                                </li>
                                <li><a href="tel:+243815034701">Phone : +243 81 503 47 01</a></li>
                                <li><a href="mailto:contact@catsr.org">Email : contact@catsr.org</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                    <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Liens Importants</h4>
                            <ul>
                                <li><a href="{% url 'app:contact' %} ">Contactez-Nous!</a></li>
                                <li><a href="{% url 'bulletin:bulletin' %}">Bulletins</a></li>
                                <li><a href="{% url 'formations:formations' %}">Formations</a></li>
                                <li><a href="{% url 'event:event' %}">Evenements</a></li>
                                <li><a href="{% url 'app:about' %}">A propos de nous!</a></li>
                                <li><a href="{% url 'app:historique' %}">Historique</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-4 col-sm-5">
                    <!-- <div class="single-footer-caption mb-50">
                        <div class="footer-tittle">
                            <h4>Newsletter</h4>
                            <div class="footer-pera footer-pera2">
                            <p>Soyez le premier à être informé en souscrivant à notre newsletter!</p>
                        </div>
                        <div class="footer-form" >
                            <div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                    method="get" class="subscribe_form relative mail_part">
                                    <input type="email" name="email" id="newsletter-form-email" placeholder="Adresse mail"
                                    class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = ' Adresse mail '">
                                    <div class="form-icon">
                                        <button type="submit" name="submit" id="newsletter-submit"
                                            class="email_icon newsletter-submit button-contactForm">
                                            <img src="{% static 'img/gallery/form.png' %}" alt="">
                                        </button>
                                    </div>
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
                        </div>
                        </div>
                    </div> -->
                </div>
            </div>
        </div>
    </div>
    <!-- footer-bottom -->
    <div class="footer-bottom-area">
        <div class="container">
            <div class="footer-border">
                <div class="row d-flex justify-content-between align-items-center">
                    <div class="col-xl-9 col-lg-8">
                        <div class="footer-copy-right">
                            <p>
                                Copyright &copy; <script>document.write(new Date().getFullYear());</script> 
                                All rights reserved
                                <i class="fa fa-heart" aria-hidden="true"></i> by 
                                <a href="https://eventdrc.com" target="_blank">Eventdrc Technology</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4">
                        <div class="footer-social f-right">
                            <!-- <a href="#"><i class="fab fa-twitter"></i></a> -->
                            <a href="https://www.linkedin.com/in/asbl-catsr-ba6a191ba"><i class="fa fa-linkedin-in"></i></a>
                            <a href="https://www.facebook.com/asbl.catsr.58"><i class="fa fa-facebook-f"></i></a>
                            <a href="https://www.instagram.com/catsrrdc/" target="blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                            <a href="https://www.youtube.com/channel/UChfw2u1YG2uiAYOs001rDwQ" target="blank"><i class="fa fa-youtube" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/nav/header.html
{% load static %}

    {% block style %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock style %}

<div class="header-area">
    <div class="main-header ">
        <div class="header-top d-none d-lg-block">
            <div class="container-fluid">
                <div class="col-xl-12">
                    <div class="row d-flex justify-content-between align-items-center">
                        <div class="header-info-left d-flex">
                            <ul>
                                <li>Phone: +243 81 503 47 01</li>
                                <li>Email: contact@catsr.org</li>
                            </ul>
                            <div class="header-social">
                                <ul>
                                    <!-- <li><a href="#" target="blank"><i class="fab fa-twitter"></i></a></li> -->
                                    <li>
                                        <a href="https://www.facebook.com/asbl.catsr.58" target="blank">
                                            <i class="fa fa-facebook-f" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.linkedin.com/in/asbl-catsr-ba6a191ba" target="blank">
                                            <i class="fa fa-linkedin-in"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.instagram.com/catsrrdc/" target="blank">
                                            <i class="fa fa-instagram" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="https://www.youtube.com/channel/UChfw2u1YG2uiAYOs001rDwQ" target="blank">
                                            <i class="fa fa-youtube" aria-hidden="true"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="header-info-right d-flex align-items-center">
                            <!-- <div class="select-this">
                                <form action="#">
                                    <div class="select-itms">
                                        <select name="select" id="select1">
                                            <option value="">Français</option>
                                            <option value="">English</option>
                                        </select>
                                    </div>
                                </form>
                            </div> -->
                            <ul class="contact-now">
                                <li><a href="{% url 'app:contact' %}">Souscris maintenant</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom  header-sticky">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <!-- Logo -->
                    <div class="col-xl-2 col-lg-2">
                        <div class="logo">
                            <a href="{% url 'app:home' %}"><img src="{% static 'img/logo/logos-catsr.jpg' %}" height="100" alt="catsr logo"></a>
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-10">
                        <div class="menu-wrapper  d-flex align-items-center justify-content-end">
                            <!-- Main-menu -->
                            <div class="main-menu d-none d-lg-block">
                                {% with request.resolver_match.url_name as url_name %}
                                    <nav>
                                        <ul id="navigation">
                                            <li class="{% if url_name == 'home' %}active{% endif %}">
                                                <a class="{% if url_name == 'home' %}active{% endif %}" href="{% url 'app:home' %}">Acceuil</a>
                                            </li>
                                            <li class="{% if url_name == 'about' %}active{% endif %}">
                                                <a class="{% if url_name == 'about' %}active{% endif %}" href="{% url 'app:about' %}">A Propos de Nous</a>
                                            </li>
                                            <li class="{% if url_name == 'bulletin' %}active{% endif %}">
                                                <a class="{% if url_name == 'bulletin' %}active{% endif %}" href="{% url 'bulletin:bulletin' %}">Activités</a>
                                            </li>
                                            <li class="{% if url_name == 'formations' %}active{% endif %}">
                                                <a class="{% if url_name == 'formations' %}active{% endif %}" href="{% url 'formations:formations' %}">Formations</a>
                                            </li>
                                            <li class="{% if url_name == 'event' %}active{% endif %}">
                                                <a href="{% url 'event:event' %}">Evénements</a>
                                            </li>
                                            <li class="d-lg-none {% if url_name == 'contact' %}active{% endif %}">
                                                <a class="d-lg-none {% if url_name == 'contact' %}active{% endif %}" href="{% url 'app:contact' %}">Contactez-Nous</a>
                                            </li>
                                        </ul>
                                    </nav>
                                {% endwith %}
                            </div>
                            <!-- Header-btn -->
                            <div class="header-right-btn d-none d-lg-block ml-20">
                                <a href="{% url 'app:contact' %}" class="btn header-btn">Contactez-Nous</a>
                            </div>
                        </div>
                    </div> 
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>